project_id = "mskdohetwbbkuexcolcl"

[functions.send-welcome-email]
verify_jwt = false

[functions.send-container-order]
verify_jwt = false

[functions.send-material-reminder]
verify_jwt = false

[functions.send-material-order]
verify_jwt = false

[functions.cleanup-scaffolding-duplicates]
verify_jwt = false

[functions.create-project-from-sale]
verify_jwt = false

[functions.get-team-availability]
verify_jwt = false

[functions.create-worker-account]
verify_jwt = false
