import { Project } from '@/types/project';
import { Notification } from '@/types/notification';

export function generateTestNotifications(projects: Project[]): Notification[] {
  const notifications: Notification[] = [
    // Team notifications (12 total)
    {
      id: 'team-1',
      type: 'team_member_added',
      category: 'team',
      priority: 'medium',
      title: 'Ny teammedlem tillagd',
      message: 'Anna Svensson har lagts till i teamet Takarbetare',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'team-2',
      type: 'team_leave_request',
      category: 'team',
      priority: 'high',
      title: 'Ledighetsansökan',
      message: 'Erik Nilsson har ansökt om ledighet nästa vecka',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'team-3',
      type: 'team_role_changed',
      category: 'team',
      priority: 'medium',
      title: 'Roll uppdaterad',
      message: 'Marcus Johansson är nu teamledare för Team A',
      projectId: projects[1]?.id || '2',
      projectName: projects[1]?.name || 'Företagsbyggnad',
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'team-4',
      type: 'team_member_added',
      category: 'team',
      priority: 'low',
      title: 'Teamförstärkning',
      message: 'Lisa Andersson ansluter till Team B på måndag',
      projectId: projects[2]?.id || '3',
      projectName: projects[2]?.name || 'Radhus Karlsson',
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'team-5',
      type: 'team_leave_request',
      category: 'team',
      priority: 'urgent',
      title: 'Akut ledighetsansökan',
      message: 'Tommy Bergström behöver sjukledighet i 3 dagar',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'team-6',
      type: 'team_role_changed',
      category: 'team',
      priority: 'medium',
      title: 'Behörighetsuppdatering',
      message: 'Petra Lindström har fått utökade behörigheter',
      projectId: projects[1]?.id || '2',
      projectName: projects[1]?.name || 'Företagsbyggnad',
      createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    
    // Planning notifications (14 total)
    {
      id: 'plan-1',
      type: 'planning_date_changed',
      category: 'planning',
      priority: 'high',
      title: 'Projektdatum ändrat',
      message: 'Startdatum för Villa Andersson har flyttats fram med 3 dagar',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'plan-2',
      type: 'planning_milestone',
      category: 'planning',
      priority: 'medium',
      title: 'Milstolpe uppnådd',
      message: 'Första byggfasen för Företagsbyggnad är nu klar',
      projectId: projects[1]?.id || '2',
      projectName: projects[1]?.name || 'Företagsbyggnad',
      createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'plan-3',
      type: 'planning_schedule_update',
      category: 'planning',
      priority: 'high',
      title: 'Schema uppdaterat',
      message: 'Arbetsschemat för nästa vecka har reviderats',
      projectId: projects[2]?.id || '3',
      projectName: projects[2]?.name || 'Radhus Karlsson',
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'plan-4',
      type: 'planning_date_changed',
      category: 'planning',
      priority: 'urgent',
      title: 'Deadline framflyttad',
      message: 'Slutdatum för Radhus Karlsson har flyttats fram 1 vecka pga väder',
      projectId: projects[2]?.id || '3',
      projectName: projects[2]?.name || 'Radhus Karlsson',
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'plan-5',
      type: 'planning_milestone',
      category: 'planning',
      priority: 'low',
      title: 'Delmål klart',
      message: 'Takstommen för Villa Andersson är färdigställd',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'plan-6',
      type: 'planning_schedule_update',
      category: 'planning',
      priority: 'medium',
      title: 'Resursplanering uppdaterad',
      message: 'Ställningsvagnar omfördelas mellan projekten',
      projectId: projects[1]?.id || '2',
      projectName: projects[1]?.name || 'Företagsbyggnad',
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    
    // Project notifications (8 total)
    {
      id: 'proj-1',
      type: 'project_created',
      category: 'project',
      priority: 'medium',
      title: 'Nytt projekt skapat',
      message: 'Projekt "Lägenhet Svensson - Balkongreparation" har skapats',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'proj-2',
      type: 'project_status_changed',
      category: 'project',
      priority: 'low',
      title: 'Projektstatus uppdaterad',
      message: 'Villa Karlsson har ändrat status till "Pågående"',
      projectId: projects[2]?.id || '3',
      projectName: projects[2]?.name || 'Radhus Karlsson',
      createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'proj-3',
      type: 'project_completed',
      category: 'project',
      priority: 'high',
      title: 'Projekt färdigställt',
      message: 'Företagsbyggnad - Plåttak har markerats som färdigt',
      projectId: projects[1]?.id || '2',
      projectName: projects[1]?.name || 'Företagsbyggnad',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'proj-4',
      type: 'project_created',
      category: 'project',
      priority: 'medium',
      title: 'Nytt akutprojekt',
      message: 'Stormskador på Villa Petterson - akut takreparation',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    
    // File notifications (6 total)
    {
      id: 'file-1',
      type: 'file_uploaded',
      category: 'files',
      priority: 'low',
      title: 'Nya filer uppladdade',
      message: 'Besiktningsprotokoll har laddats upp för Villa Andersson',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'file-2',
      type: 'file_shared',
      category: 'files',
      priority: 'medium',
      title: 'Filer delade',
      message: 'Tekniska ritningar har delats med team B för Företagsbyggnad',
      projectId: projects[1]?.id || '2',
      projectName: projects[1]?.name || 'Företagsbyggnad',
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
    {
      id: 'file-3',
      type: 'file_updated',
      category: 'files',
      priority: 'high',
      title: 'Viktiga dokument uppdaterade',
      message: 'Säkerhetsprotokoll för Radhus Karlsson har reviderats',
      projectId: projects[2]?.id || '3',
      projectName: projects[2]?.name || 'Radhus Karlsson',
      createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    
    // General notifications (6 total)
    {
      id: 'gen-1',
      type: 'material_order',
      category: 'general',
      priority: 'urgent',
      title: 'Brådskande materialbeställning',
      message: 'Material för takpannor behöver beställas innan imorgon',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'gen-2',
      type: 'checklist_incomplete',
      category: 'general',
      priority: 'high',
      title: 'Säkerhetschecklista ofullständig',
      message: 'Säkerhetscheck för Företagsbyggnad saknar 3 punkter',
      projectId: projects[1]?.id || '2',
      projectName: projects[1]?.name || 'Företagsbyggnad',
      createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'gen-3',
      type: 'inspection_missing',
      category: 'general',
      priority: 'medium',
      title: 'Slutbesiktning saknas',
      message: 'Radhus Karlsson behöver slutbesiktning inom 5 dagar',
      projectId: projects[2]?.id || '3',
      projectName: projects[2]?.name || 'Radhus Karlsson',
      createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: true,
    },
    {
      id: 'gen-4',
      type: 'deadline_warning',
      category: 'general',
      priority: 'low',
      title: 'Deadline påminnelse',
      message: 'Villa Andersson - 3 dagar kvar till deadline',
      projectId: projects[0]?.id || '1',
      projectName: projects[0]?.name || 'Villa Andersson',
      createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
      isRead: false,
      actionRequired: false,
    },
  ];
  
  return notifications;
}