// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://mhcclxzrsffbankzftjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oY2NseHpyc2ZmYmFua3pmdGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTE4NzcsImV4cCI6MjA3MjQyNzg3N30.UAkTcUV-kEpTorqw7uWMvRaQku9HjzVRljBM357QGoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
